loan-api:
  mongo:
    url: ${ENVIORNMENT_DATABASE_URL}
    db: ${ENVIORNMENT_DATABASE_NAME}
spring:
  jpa:
    show-sql: true
logging:
  level:
    com.querydsl.sql: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG